In [19]:
import numpy as np

In [25]:
W1 = np.random.randn(3, 4)
b1 = np.zeros((1, 4))
W2 = np.random.randn(4, 1)
b2 = np.zeros((1, 1))


X = np.random.randn(1, 3)


Z1 = np.dot(X, W1) + b1
A1 = np.maximum(0, Z1)  # ReLU activation
Z2 = np.dot(A1, W2) + b2
Y_pred = Z2  # Linear activation for the output layer

# Loss calculation (MSE)
Y_true = 1
L = np.mean((Y_true - Y_pred)**2)

print(W1, b1, W2, b2)

Y_pred, L, X

[[-1.38732634  0.31231542 -0.08158188 -1.08611046]
 [ 0.44945692  1.87727515 -0.11459003 -0.40123467]
 [-0.93499266 -0.4396549  -0.06301106  0.31843441]] [[0. 0. 0. 0.]] [[-0.73726954]
 [ 1.13236436]
 [ 0.48907067]
 [ 1.18368968]] [[0.]]


(array([[0.48873909]]),
 0.2613877134275396,
 array([[-0.10244895,  0.43508093, -0.81313071]]))

In [21]:
# Compute gradients for the output layer
dZ2 = 2 * (Y_pred - Y_true)  # Derivative of MSE loss with respect to Z2
dW2 = np.dot(A1.T, dZ2)
db2 = np.sum(dZ2, axis=0, keepdims=True)

# Compute gradients for the hidden layer
dA1 = np.dot(dZ2, W2.T)
dZ1 = dA1 * (Z1 > 0)  # Derivative of ReLU activation
dW1 = np.dot(X.T, dZ1)
db1 = np.sum(dZ1, axis=0, keepdims=True)

In [22]:
learning_rate = 0.1

W2 = W2 - learning_rate * dW2
b2 = b2 - learning_rate * db2


W1 = W1 - learning_rate * dW1
b1 = b1 - learning_rate * db1

print(W1, b1, W2, b2)

[[-0.47326784  0.1957852  -1.02812372  0.60239286]
 [-1.05680007  0.12566982 -2.08446374 -1.78786444]
 [ 0.43295509 -1.60741735  1.45988432  0.35988672]] [[ 0.28129526  0.         -0.05304312 -0.02272583]] [[1.4651426 ]
 [1.16665467]
 [0.4654551 ]
 [0.12325311]] [[0.21277135]]
